[package]
name    = "conway_coro"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe  = "0.24"
egui    = "0.24"
tokio   = { version = "1.0", features = ["full"] }
winapi  = { version = "0.3", features = ["winuser", "windef"] }


